version: '3.4'

services:
  granitotest.calcapi:
    image: ${DOCKER_REGISTRY-}granitotestcalcapi
    ports:
      - "5000:80"
    build:
      context: .
      dockerfile: GranitoTest.CalcApi/Dockerfile
    depends_on:
      - granitotest.taxapi
    links: 
      - granitotest.taxapi
    networks:
      - docker_network
  granitotest.taxapi:
    image: ${DOCKER_REGISTRY-}granitotesttaxapi
    ports:
      - "5001:81"
    build:
      context: .
      dockerfile: GranitoTest.TaxApi/Dockerfile
    networks:
      - docker_network
networks:
  docker_network:
    driver: bridge